"""create sources and articles tables

Revision ID: 5241ab85f76a
Revises: 
Create Date: 2025-04-24 18:05:57.780158

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5241ab85f76a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_sources_id'), 'sources', ['id'], unique=False)
    op.add_column('articles', sa.Column('source_id', sa.Integer(), nullable=True))
    op.drop_index('ix_articles_source', table_name='articles')
    op.create_foreign_key(None, 'articles', 'sources', ['source_id'], ['id'])
    op.drop_column('articles', 'source')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('source', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'articles', type_='foreignkey')
    op.create_index('ix_articles_source', 'articles', ['source'], unique=False)
    op.drop_column('articles', 'source_id')
    op.drop_index(op.f('ix_sources_id'), table_name='sources')
    op.drop_table('sources')
    # ### end Alembic commands ###
