"""add firebase_uid to users table

Revision ID: 6ad9a0b7d4b7
Revises: 9f9cfecf9cb7
Create Date: 2025-11-21 11:36:48.577323

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6ad9a0b7d4b7"
down_revision: Union[str, None] = "9f9cfecf9cb7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Add firebase_uid column
    op.add_column("users", sa.Column("firebase_uid", sa.String(), nullable=True))
    op.create_index(
        op.f("ix_users_firebase_uid"), "users", ["firebase_uid"], unique=True
    )

    # SQLite doesn't support ALTER COLUMN, so we'll handle nullable hashed_password
    # by creating new table and copying data if needed
    # For now, we'll leave existing users with non-null hashed_password


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_firebase_uid"), table_name="users")
    op.alter_column(
        "users", "hashed_password", existing_type=sa.VARCHAR(), nullable=False
    )
    op.drop_column("users", "firebase_uid")
    # ### end Alembic commands ###
