"""fix article language column

Revision ID: 93468b73bc87
Revises: 5241ab85f76a
Create Date: 2025-04-28 22:28:35.231335

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '93468b73bc87'
down_revision: Union[str, None] = '5241ab85f76a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('language', sa.String(), nullable=True))
    op.add_column('articles', sa.Column('country', sa.String(), nullable=True))
    op.add_column('articles', sa.Column('category', sa.String(), nullable=True))
    op.alter_column('articles', 'source_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_bookmarks_id'), 'bookmarks', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bookmarks_id'), table_name='bookmarks')
    op.alter_column('articles', 'source_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('articles', 'category')
    op.drop_column('articles', 'country')
    op.drop_column('articles', 'language')
    # ### end Alembic commands ###
