"""Add crawl_jobs, article_contents, and sentiment_analyses tables

Revision ID: 9f9cfecf9cb7
Revises: ae63b0495c28
Create Date: 2025-11-18 14:53:55.298247

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9f9cfecf9cb7"
down_revision: Union[str, None] = "ae63b0495c28"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "article_contents",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("article_id", sa.Integer(), nullable=False),
        sa.Column("content_text", sa.Text(), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("content_length", sa.Integer(), nullable=False),
        sa.Column("extracted_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["article_id"], ["articles.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("article_id"),
    )
    op.create_index(
        "ix_article_contents_content_hash",
        "article_contents",
        ["content_hash"],
        unique=False,
    )
    op.create_index(
        "ix_article_contents_expires_at",
        "article_contents",
        ["expires_at"],
        unique=False,
    )
    op.create_index(
        "ix_article_contents_extracted_at",
        "article_contents",
        ["extracted_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_article_contents_id"), "article_contents", ["id"], unique=False
    )
    op.create_table(
        "crawl_jobs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("article_id", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "IN_PROGRESS",
                "SUCCESS",
                "FAILED",
                "FORBIDDEN_BY_ROBOTS",
                "RATE_LIMITED",
                name="crawlstatus",
            ),
            nullable=False,
        ),
        sa.Column("robots_allowed", sa.Boolean(), nullable=True),
        sa.Column("http_status", sa.Integer(), nullable=True),
        sa.Column("fetched_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("bytes_downloaded", sa.Integer(), nullable=True),
        sa.Column("error_code", sa.String(length=50), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["article_id"], ["articles.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_crawl_jobs_article_id", "crawl_jobs", ["article_id"], unique=False
    )
    op.create_index(
        "ix_crawl_jobs_created_at", "crawl_jobs", ["created_at"], unique=False
    )
    op.create_index(op.f("ix_crawl_jobs_id"), "crawl_jobs", ["id"], unique=False)
    op.create_index("ix_crawl_jobs_status", "crawl_jobs", ["status"], unique=False)
    op.create_table(
        "sentiment_analyses",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("article_id", sa.Integer(), nullable=False),
        sa.Column("provider", sa.String(length=50), nullable=False),
        sa.Column("model_name", sa.String(length=100), nullable=True),
        sa.Column("score", sa.Float(), nullable=False),
        sa.Column("magnitude", sa.Float(), nullable=True),
        sa.Column("label", sa.String(length=20), nullable=False),
        sa.Column("language", sa.String(length=10), nullable=True),
        sa.Column("analyzed_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["article_id"], ["articles.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_sentiment_analyses_analyzed_at"),
        "sentiment_analyses",
        ["analyzed_at"],
        unique=False,
    )
    op.create_index(
        "ix_sentiment_analyses_article_id",
        "sentiment_analyses",
        ["article_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_sentiment_analyses_id"), "sentiment_analyses", ["id"], unique=False
    )
    op.create_index(
        "ix_sentiment_analyses_label", "sentiment_analyses", ["label"], unique=False
    )
    op.create_index(
        "ix_sentiment_analyses_provider",
        "sentiment_analyses",
        ["provider"],
        unique=False,
    )
    op.create_index(
        "ix_sentiment_analyses_provider_article",
        "sentiment_analyses",
        ["provider", "article_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_sentiment_analyses_provider_article", table_name="sentiment_analyses"
    )
    op.drop_index("ix_sentiment_analyses_provider", table_name="sentiment_analyses")
    op.drop_index("ix_sentiment_analyses_label", table_name="sentiment_analyses")
    op.drop_index(op.f("ix_sentiment_analyses_id"), table_name="sentiment_analyses")
    op.drop_index("ix_sentiment_analyses_article_id", table_name="sentiment_analyses")
    op.drop_index(
        op.f("ix_sentiment_analyses_analyzed_at"), table_name="sentiment_analyses"
    )
    op.drop_table("sentiment_analyses")
    op.drop_index("ix_crawl_jobs_status", table_name="crawl_jobs")
    op.drop_index(op.f("ix_crawl_jobs_id"), table_name="crawl_jobs")
    op.drop_index("ix_crawl_jobs_created_at", table_name="crawl_jobs")
    op.drop_index("ix_crawl_jobs_article_id", table_name="crawl_jobs")
    op.drop_table("crawl_jobs")
    op.drop_index(op.f("ix_article_contents_id"), table_name="article_contents")
    op.drop_index("ix_article_contents_extracted_at", table_name="article_contents")
    op.drop_index("ix_article_contents_expires_at", table_name="article_contents")
    op.drop_index("ix_article_contents_content_hash", table_name="article_contents")
    op.drop_table("article_contents")
    # ### end Alembic commands ###
