"""Fix schemas to pydantic v2

Revision ID: a25a4e6750e1
Revises: 033994d9eedb
Create Date: 2025-04-30 15:59:43.291820

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "a25a4e6750e1"
down_revision: Union[str, None] = "033994d9eedb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
